version: "3.7"

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
  backend:
    container_name: sadiq_restaurant_backend
    restart: always
    build:
      context: .
      extra_hosts:
        - host.docker.internal:host-gateway
    environment:
      - APP_ENV=development
      - APP_PORT=9001
    volumes:
      - ./src:/var/www/sadiq_restaurant/src
      - ./test:/var/www/sadiq_restaurant/test
    working_dir: /var/www/sadiq_restaurant
    ports:
      - "9001:9001"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: sadiq_restaurant_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root=root
      - MYSQL_PASSWORD==root
      - MYSQL_DATABASE=credit
    ports:
      - "3306:3306"
    volumes:
      - sadiq_restaurant_mysql_data:/var/lib/mysql

volumes:
  sadiq_restaurant_mysql_data:

networks:
  default:
    external:
      name: sadiq_restaurant




